title: Vedic-Aryan
description: > # this means to ignore newlines until "baseurl:"
  Learn Play Explore with vedic-aryan"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vedic-aryan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:

# Author Settings
author: Vedic-Aryan
author-img: vedic-aryan.jpg
about-author: I'm a kids yoga practitioner in Australia and India. If not already joined, you may subscribe my YouTube channel https://www.youtube.com/@vedic-aryan
social-twitter:
social-facebook:
social-github: vedic-aryan
social-linkedin:
social-email:

# Disqus
discus-identifier:

# Tracker
analytics:

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
