title: Vedic-Aryan
description: > # this means to ignore newlines until "baseurl:"
  Learn Play Explore with vedic-aryan"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vedic-aryan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Aryan Rawat # add your name
author-img: vedic-aryan.jpg # add your photo
about-author: I'm a kids yoga practitioner in Australia # add description
social-twitter:  # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: vedic-aryan # ig handle
social-linkedin: # add your Linkedin handle
social-email:  # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
